### ISSUE TITLE
Simulator - Error message

### ISSUE THREAD

**Issue by daniel-kozlovsky** [AkinAD/ExMech#1]
When one event exists and the simulator is played, it reads an error message.

**Reproduction**

-Start application and choose new scenario
-Add an "add text" event with "t" as the text
-Click "Simulate Story" from the "Simulate" drop down

**Results**

This will play an error message, spoken by the systems default voice. The error will repeat twice and then the "add text" event will be played as intended. As a side note, the voice keeps playing even when the window is closed. 

**Expected**

The whole "story" should play without error messages.

**Build**

February 23rd 2018 on Windows 7 Professional 64-bit
Java: 1.8.0_151

**Comment by philipn7** [comment]
Can not replicate issue.
