### ISSUE TITLE
Audio Recorder - Cancelling a recording breaks future ability to record

### ISSUE THREAD

**Issue by ArshdeepSaini** [AkinAD/ExMech#2]
When the user is recording audio and closes the dialog before finishing recording, future attempts to record are not possible.

_**Steps to reproduce:**_
1. Start the program and select **New Story**
2. Click **Audio Recording**
3. Click **Capture**
4. Close the dialog
5. Click **Audio Recording** again
6. Attempt to record by clicking **Capture** again

_**Expected behavior:**_
The dialog, opened the second time, should be able to function as intended, recording audio successfully.

_**Actual behavior:**_
Clicking **Capture** abruptly closes the dialog.

_**Testing machine:**_
Windows 10 Home (64 bit)

**Comment by AkinAD** [comment]
Hello! 
Thank you for bringing this bug to our notice, we have fixed it and you'll be able to see the changes in our next release.
Cheers!
Akin
